sudo: required
services:
  - docker

before_install:
  - docker build -t yadjanor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yadjanor/react-test npm test

after_success:
  - docker build -t yadjanor/multi-client ./client
  - docker build -t yadjanor/multi-ngnix ./ngnix
  - docker build -t yadjanor/multi-server ./server
  - docker build -t yadjanor/multi-worker ./worker
  # Log in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push to DockerHub
  - docker push yadjanor/multi-client
  - docker push yadjanor/multi-ngnix
  - docker push yadjanor/multi-server
  - docker push yadjanor/multi-worker



